# Generated by Django 5.2.14 on 2026-05-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_remove_transcriptentry_add_raw_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='consultation',
            name='recall_bot_id',
            field=models.CharField(blank=True, default='', help_text='Recall.ai bot UUID. Set after bot is created. Used to match webhooks.', max_length=255),
        ),
        migrations.AddField(
            model_name='consultation',
            name='zoom_join_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='consultation',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='zoom_password',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='zoom_start_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('processing', 'Processing'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
