# Generated by Django 5.2.14 on 2026-05-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_consultation_zoom_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
