# Generated by Django 5.2.14 on 2026-05-10 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_simplejwt_outstandingtoken_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, default='', max_length=255)),
                ('template_preference', models.CharField(choices=[('soap', 'SOAP Note'), ('hp', 'H&P'), ('progress', 'Progress Note'), ('custom', 'Custom')], default='soap', max_length=20)),
                ('custom_template_name', models.CharField(blank=True, default='', max_length=255)),
                ('example_note', models.TextField(blank=True, default='', help_text='De-identified example note used to personalise AI output style.')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
