# Generated by Django 5.2.14 on 2026-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='care_plan',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
